### ISSUE TITLE
smart_punct.txt

### ISSUE THREAD

**Issue by iamstarkov** [jgm/cmark#30]
We have already discussed it commonmark.js, but I spotted test for smart punctuation here. And have the same question. Why does markdown transformer have responsibility to do smth with typography?

**Comment by jgm** [comment]
+++ Vladimir Starkov [Apr 29 15 14:39 ]:
>   We have already discussed it commonmark.js, but I spotted test for
>   smart punctuation here. And have question. Why does markdown
>   transformer have responsibility to do smth with typography?

1. Because doing the typographic transformations on the rendered HTML doesn't allow you to escape the punctuation symbols when you don't want them to be converted.  With our method we can do:  `these are "curly" and these are \"straight\"`.

2. Because if we do it in the parser, we can use the result in every output format we support.

**Comment by iamstarkov** [comment]
You are totally right, and I was not clear with my point of view. My point is that, commonmark should use 3rd party extension for this, and not complicate itself

**Comment by jgm** [comment]
+++ Vladimir Starkov [Apr 29 15 16:21 ]:
>   You are totally right, and I was not clear with my point of view. My
>   point is that, commonmark should use 3rd party extension for this, and
>   not complicate itself

Well, if the work needs to be done at the parsing stage, then it needs to go into the commonmark parser.  (In principle one might find a way to make the parser extensible through third-party plugins -- markdown-it, a javascript project, does that -- but cmark isn't that way.)

**Comment by iamstarkov** [comment]
> cmark isn't that way.

Isn’t it contra to statement about commonmark? part about _unambiguous_ and _reliably on every platform_

> We believe a complete, unambiguous CommonMark specification will promote adoption of Markdown and ensure that Markdown documents continue to render reliably in the future on every platform.

All the commonmark need is to expose some way to process text inside the compilation process. Can we do it?

**Comment by iamstarkov** [comment]
If end user/customer want md2html compiler, then commonmark should give it, not less, and not more. Am I doing it wrong?

**Comment by jgm** [comment]
+++ Vladimir Starkov [Apr 30 15 06:05 ]:
>> cmark isn't that way.
>
>Isn’t it contra to statement about commonmark? part about _unambiguous_ and _reliably on every platform_

`--smart` is just an option.

>> We believe a complete, unambiguous CommonMark specification will promote adoption of Markdown and ensure that Markdown documents continue to render reliably in the future on every platform.
>
>All the commonmark need is to expose some way to process text inside the compilation process. Can we do it?

It's not that easy.  Lots of things have to change in the parsing process
(e.g. we have to recognize that " might be a special character).

**Comment by iamstarkov** [comment]
> It's not that easy.  Lots of things have to change in the parsing process

it’s okay in longterm if it proper way of doing things, isn’t it? we can create checklist for this.  
I’m thinking in terms of streaming (and processing) text values while walking on AST node

I didn’t get the point `"` of special character.

**Comment by jgm** [comment]
> I’m thinking in terms of streaming (and processing) text values while walking on AST node

This won't work.  Once we get to text nodes in the AST, there is no distinction between escaped `\"` and unescaped `"`.  If we want only unescaped `"` to be treated as "smart," then we need to recognize quoted sections in the parser, before the text node is created.

**Comment by iamstarkov** [comment]
I’m not talking about quotes at all.

**Comment by iamstarkov** [comment]
For example:

```md
# title with a "quotes"
```

then commonmark will kind of emit one object to a stream with content like this: `title with a "quotes"`

**Comment by jgm** [comment]
+++ Vladimir Starkov [Apr 30 15 10:07 ]:
>I’m not talking about quotes at all.

What are you talking about, then?

Quotes are one of the main things smart punctuation is designed to
handle.   If that can't be handled by walking the AST, then we need
to handle smart punctuation in the parser.

**Comment by iamstarkov** [comment]
> What are you talking about, then?

I’m talking about delegation. If commonmark can delegate it to 3rd party engine, then it should. For example by emitting pure text nodes of AST tree to some kind of typo-processor.

**Comment by iamstarkov** [comment]
> Quotes are one of the main things smart punctuation is designed to
handle.   If that can't be handled by walking the AST, then we need
to handle smart punctuation in the parser.

Sorry, I don’t want to be offensive, but I’m still obsessed with typography. It’s very complicated and error-prone process. If we can delegate, we should.

**Comment by iamstarkov** [comment]
At least, It will make maintainship less stressfull. and to be honest typography is not and should not be a responsibility of markdown processor

**Comment by jgm** [comment]
> I’m talking about delegation. If commonmark can delegate it to 3rd party engine, then it should. For example by emitting pure text nodes of AST tree to some kind of typo-processor.

I already explained the technical problem with this approach.  The text nodes of the AST don't contain enough information to do proper smart quote substitution.  There are a couple of reasons for this: one, which I already mentioned, is that the text nodes don't carry information about which quotation marks were escaped in the source.  Another reason, which I haven't mentioned, is that proper smart quote replacement requires intelligent matching of quotes, which requires knowing more about the context than you know if you just have text nodes.  (I mention in [this forum post](http://talk.commonmark.org/t/spec-0-18-release/1084) that our smart quote parsing is more accurate than most others because of this.)

If it were technically feasible to handle smart typography in a separate engine, I'd be for that.  But I don't think you're appreciating the technical difficulties.  This is something I thought quite a bit about before implementing the smart punctuation feature.

If you want to make a detailed proposal about how this could be done, go for it.  Otherwise, I don't think there's point discussing further in the abstract.

**Comment by jgm** [comment]
I'm closing this issue: feel free to open a new one if you come up with a determinate proposal.  I think that if you try to create code that processes the AST, you'll come to see the difficulties I noted above.  Maybe there's a good way around them.  No better way to find out than to produce working code that passes the tests.
