### ISSUE TITLE
Warning on Solaris 11

### ISSUE THREAD

**Issue by jeroenooms** [jgm/cmark#41]
When building with SolarisStudio 12.3

```gcc
root@solaris11:~/Desktop/cmark/build# make
Scanning dependencies of target cmark
[  1%] Building C object src/CMakeFiles/cmark.dir/cmark.c.o
"/root/Desktop/cmark/src/buffer.h", line 96: warning:  attribute "format" is unknown, ignored
[  3%] Building C object src/CMakeFiles/cmark.dir/node.c.o
"/root/Desktop/cmark/src/buffer.h", line 96: warning:  attribute "format" is unknown, ignored
[  5%] Building C object src/CMakeFiles/cmark.dir/iterator.c.o
"/root/Desktop/cmark/src/buffer.h", line 96: warning:  attribute "format" is unknown, ignored
[  7%] Building C object src/CMakeFiles/cmark.dir/blocks.c.o
"/root/Desktop/cmark/src/buffer.h", line 96: warning:  attribute "format" is unknown, ignored
...
```

**Comment by nwellnhof** [comment]
We'd need a feature test for the `format` attribute to resolve this, similar to the test for attribute support: https://github.com/jgm/cmark/blob/0e4769d5c1e254fa1747701d2da708d0cb61d0c3/src/CMakeLists.txt#L136

Since only a warning is generated, the test must either check the stderr output, or it must be compiled with warnings as errors (`-Werror` for GCC, `-errwarn=%all` for Solaris Studio (Sun C), `/WX` for MSVC). Unfortunately, this complicates things a lot.

**Comment by jgm** [comment]
Since it's just a warning, I'm inclined not to complicate things too much.
