### ISSUE TITLE
CRLF regression with fenced code

### ISSUE THREAD

**Issue by btrask** [jgm/cmark#71]
Thank you for making quick work of #68, but I'm afraid that's not the end of it.

Example input:

>     ```
>     test
>     ```

Output:

>     <pre><code>test
>     ```</code></pre>

This happens with or without the `--hardbreaks` option.

**Comment by jgm** [comment]
Can't reproduce.
```
 % perl -pe 's/\n/\r\n/g' | ./cmark
```
test
```
^D
<pre><code>test
</code></pre>
```

**Comment by jgm** [comment]
Did your input have no line ending character (cr, lf, crlf) after the final line?
With that I can reproduce.
That's because the close-fence scanner is looking for a final line ending character.
There used to be some code that added a line ending character to a line if none was present; I assume that's what got messed up in the last batch of changes.

**Comment by btrask** [comment]
Oh, you're right. Sorry for jumping to conclusions!

I briefly tested a few other things and I didn't find any other problems. Thank you!

**Comment by jgm** [comment]
I found two more issues by modifying line endings in the
test suite.  See #73.

+++ Ben Trask [Aug 08 15 13:31 ]:

**Comment by jgm** [comment]
See also #72.

**Comment by btrask** [comment]
Great work! Thanks for making line endings a priority. :)
